spring:
  profiles:
    active: prod

  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: ${spring.datasource.driver-class-name}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

google:
  client:
    id: ${google.client.id}
    secret: ${google.client.secret}
  redirect:
    uri: ${google.redirect.uri}

oauth:
  kakao:
    rest-api-key: ${oauth.kakao.rest-api-key}
    redirect-url: ${oauth.kakao.redirect-url}