spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://localhost:3306/login
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: true

jwt:
  secret: ${jwt.secret}
  access-token-validity-in-milliseconds: ${jwt.access-token-validity-in-milliseconds}

oauth:
  naver:
    request-token-uri: ${oauth.naver.request-token-uri}
    secret: ${oauth.naver.secret}
    client-id: ${oauth.naver.client-id}

client-id: ${client-id}
client-secret: ${client-secret}